### ISSUE TITLE
Button/Form controls to have disabled appearance with enabled interactivity

### ISSUE THREAD

**Issue by Guria** [reshaped/community#1]
Having diabled UI element often could be considered harmfull for UX.
User may not have understanding of the actual reason why it is disabled.

There is a pattern when we apply disabled appearance and readonly state to control, so:
- Buttons could be passed with special onClick handler to provide proper feedback to user about reason it appeared disabled.
- Inputs in readonly mode allows text selection with mouse and keyboard therefore having better accessibility compared to its disabled counterpart.

**Comment by Guria** [comment]
@blvdmitry any thoughts on this part? I'd ;ike to hear your opinion on this topic

**Comment by blvdmitry** [comment]
That's a good one. I have it on my "planned tasks" list and if that's something you would need I could prioritise this one. I've started with disabled because that's the most straightforward approach supported natively (for instance, while javascript is still loading). 

I think the first thing here would be to review what others are doing to solve this, so if you have any examples of components handling this well – please share links.

**Comment by blvdmitry** [comment]
@Guria After looking for some information around the internet I found that in most related github discussions developers agree to wrap disabled buttons with an additional element and assign Tooltip event handlers to it. The only important part to notice here is that those elements should be made focusable. I'll add this documentation improvement for the next minor release.

**Comment by blvdmitry** [comment]
Got the documentation updated locally, it's waiting for the next release now. Thanks for raising up this question!

![image](https://user-images.githubusercontent.com/887379/126910017-8764093e-cc8c-4696-b7a4-1452ecd96e90.png)

**Comment by Guria** [comment]
Hm. Not quite what I meant, actually.
I will add a follow up tomorrow with examples and references.

**Comment by blvdmitry** [comment]
Sure, let's keep this open then

**Comment by Guria** [comment]
Okay. Actually I really like tooltip solution. It is really nice unobtrusive way to report why Button isn't available.
And `Actionable` could be also used to have custom onClick handler to use some generic notifications available in app.
The only drawback here I see it is a way how to define it conditionally. We do not need Actionable wrapper for non-disabled states. 
```jsx

function () {
  // ...
  return disabled ? (
    <Tooltip text={disabledReason}>
      {
        ({ attributes }) => (
          <Actionable attributes={attributes} as="div">
            <Button disabled>Trigger</Button>
          </Actionable>
        )
      }
    </Tooltip>
  ) : (
    <Tooltip text={tooltipText}>
      {
        ({ attributes }) => (
          <Button attributes={attributes}>Trigger</Button>
        )
      }
    </Tooltip>
  )
}
```
We can use [ConditionalWrap Component](https://arjayosma.com/how-to-conditionally-wrap-a-react-component/) to improve it a bit, but still would be tricky since `attributes` could go to a different component based on condition.

Another case we are not still solving with a wrapper is an ability to select and copy text from disabled Input. It can be achieved natively by using `readonly` attribute.

My actual suggestion would be to introduce `pseudoDisabled` prop. Both for Button and TextField it would apply disabled appearance.
For TextField it would add `readonly` to resulting input element making change event handlers unable to trigger.
For Buttons we will still allow triggering focus / click handlers. It would be consumer side responsibility to replace appropriate click handler conditioanally.
```jsx
function () {
  // ...
  return (
    <Tooltip text={disabled ? disabledReason : tooltipText}>
      {
        ({ attributes }) => (
          <Button
            attributes={attributes}
            pseudoDisabled={disabled}
            onClick={disabled ? showDisabledReasonNotification : onClick}
          >
            Trigger
          </Button>
        )
      }
    </Tooltip>
  )
}
```

**Comment by Guria** [comment]
Some related links:
https://uxdesign.cc/why-heuristics-are-only-rules-of-thumb-the-case-of-the-disabled-button-4824958627e9
https://uxdworld.com/2021/07/09/design-tip-10-dont-use-disabled-buttons/
https://stories.justinewin.com/disabled-buttons-dont-have-to-suck-10da0bb6d37e

A bit unrelated but still worth to check:
https://uxmovement.com/buttons/why-you-shouldnt-gray-out-disabled-buttons/

I do understand that my suggestion could be pretty opinionated so you are free to interpret it.

**Comment by blvdmitry** [comment]
I'll just use this issue to think out loud, I think the button use case and input use case might be two different cases.

For the inputs, readonly is an attribute supported natively, so it can already be used with `inputAttributes={{ readOnly: true }}`. 

For buttons I wonder if there is just a better to wrap it without adding a new property (don't get me wrong, I'm just always inclined to try my best and solve the problem with current means and adding a prop later will still be a simple fallback in case there is no other option). Additionally, pseudoDisabled might not work correctly while JS is still loading if it's not handled by html.

In this specific example, it can be shortened a bit already I guess:
```
<Tooltip text={disabled ? disabledReason : tooltipText}>
      {
        ({ attributes }) => {
          const button = <Button disabled>Trigger</Button>;

          if (disabled) return <Actionable attributes={attributes} as="div">{button}</Actionable>;
         return button;
        }
      }
</Tooltip>
```
