### ISSUE TITLE
Doing Icon & Aspect Ratio more intuitive?

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#100]
Dealing with Aspect Ratio, SVGs and % numbers with CSS is not the most trivial thing what I experienced. It would be great, if this headache could be solved intuitive in Reshape.

Given:
```jsx
'use client'
import { AspectRatio, Icon, View } from "../Reshaped/Reshaped";

const RootSvg = () => (
    <svg
        width="21"
        height="45"
        viewBox="0 0 21 45"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            d="M1.17643 43.8197L0.514681 43.8984C0.622289 43.4907 0.795664 43.0085 1.00945 42.4426C1.06166 42.3044 1.11615 42.1616 1.17228 42.0145C1.35337 41.5397 1.55145 41.0204 1.74446 40.4702C2.25157 39.0244 2.73952 37.3224 2.85637 35.4513C2.97847 33.4962 3.08464 31.3692 3.19489 29.1603C3.46591 23.7306 3.76164 17.8059 4.37947 12.7213C4.81415 9.14403 5.40381 6.02807 6.23923 3.81785C6.65728 2.71184 7.12422 1.8676 7.63656 1.30713C8.14046 0.755885 8.66623 0.500023 9.2344 0.5C10.7547 0.499939 12.0063 1.58845 13.0514 3.73069C14.0902 5.85991 14.8441 8.87994 15.4212 12.3967C16.2177 17.2507 16.6634 22.9462 17.0891 28.3861C17.2805 30.8315 17.4678 33.2252 17.6811 35.4675C17.8564 37.3097 18.4311 39.0327 19.0216 40.5634C19.1929 41.0074 19.3633 41.4306 19.5261 41.8347C19.9249 42.825 20.2777 43.7009 20.4836 44.4877C14.1146 43.2803 7.60893 43.0551 1.17643 43.8197Z"
        />
    </svg>
)

export default function Tooth() {
    return (
        <View width="100px" height="100px">
            <AspectRatio ratio={2 / 1}>
                <Icon svg={RootSvg} size={15} />
            </AspectRatio>
        </View>
    )
}
```

## 1. Sizing

View is 100 x 100 (That what I expect)
![image](https://user-images.githubusercontent.com/87228994/209797594-6987f7ca-1e6a-45b6-9487-e015ad2a048c.png)

Aspect Ratio is 100 x 60 ( I would expect 100 x 50, because 2 / 1)
![image](https://user-images.githubusercontent.com/87228994/209797641-124d72b1-4aa8-4f20-92a0-c952a4f8d23b.png)

## 2. SVG Grow

Currently, I can assign to an SVG a `Responsive Numbers` that changes based on the Viewport. On top of it, it would be great to be able to assign % numbers or a `grow={true}` property.
In our case, I would like, that the SVG is every time growing up to the container size, and maintaining the Aspect Ratio at the same time.

=> `<Aspect Ratio ratio={2 / 1}>` = 100 x 50
=> `<Icon svg={RootSvg} grow={true}` = 23 x 50

**Comment by mmailaender** [comment]
Btw. is it on purpose, that `<View>` is not having `position: relative` set? If I'm working with a component, that scales based on the parent size, it will not work at the moment. e.g. Nextjs image `fill` property: https://beta.nextjs.org/docs/api-reference/components/image#fill

**Comment by blvdmitry** [comment]
1. Sizing: So I see this happens because Icon has both width and height defined by the size prop. It's using both to make sure when you use different icons in the lists, they would respect the same boundaries and will keep the text content aligned. To change this behaviour – there is an `autoWidth` property. That will keep the icon size defined by its height, which  still doesn't work well with css aspect-ratio. Can you share more about the use case you're trying to solve?

2. I think it's related to a broader question as well. We have some components that work with string units (e.g. width="100px", height="100%") and some work with numbers as unit multipliers. One of our original ideas was to support both in all cases and always resolve numbers as multipliers, but that's not super straightforward since developers are also used to how React resolves numbers to px. I'm leaning towards supporting string values for the icon size, but this will affect the future decisions in this area as well.

3. It's partially on purpose. That's a common requirement I've noticed while building various pages and examples in the past, so maybe the best option here is to provide a position prop to View with relative being default. (One day View will cover everything Tailwind does, haha :D). What do you think about it?

**Comment by blvdmitry** [comment]
Here is how it works with `autoWidth` by the way: 
<img width="216" alt="image" src="https://user-images.githubusercontent.com/887379/209874944-5d9cf341-d455-4d1f-8c51-6e6d24394455.png">

1. Icon height gets set to 15 * 4 = 60px
2. Ratio sets Icon wrapper span and makes it 120x60 because of 2/1 ratio. Icon SVG doesn't get center though because it's not supported right now. Would you expect svg to get centered in this case or stretched? (I'd personally say centered)
3. AspectRatio gets width of 100x60 because it's limited by the parent size 
4. View is 100x100 based on the defined size

**Comment by mmailaender** [comment]
First, sorry for the delayed answer. Was knocked out because of #flu

## 1. Sizing
We have two use cases:

- Automatic SVG growing
- SVG composition

### Automatic SVG growing
So instead of telling an SVG a static size, I would like that it takes the space that is available from the parent. So that it grows dynamically. With that, I can implement responsiveness more fluid and faster. The solution for this is in my eyes the 2. point.

### SVG compositions
We're composing SVGs like this tooth which is composed out of 4 SVGs:
![image](https://user-images.githubusercontent.com/87228994/211010561-6961279d-a91c-42f1-abcf-b13b6dbb62ac.png)

Every SVG is an own component, so we can reuse them and recompose based on the concrete use case. e.g. in one use case we need only the crown:
![image](https://user-images.githubusercontent.com/87228994/211010772-746998f8-8aef-439b-82ff-72e609b1b2f7.png)

To achieve in this case automatic SVG growing, I need aspect ratio. A single SVG is self ensuring the own aspect ratio. But multiple can't. So the container needs to ensure it.

Probably the solution should be the 2. and 3. point. The SVG needs to be scaled based on `width: 100%` and `height: 100%`. Then the `<AspectRatio>` probably should work. And with `<View position="relative" / "absolute">` I could compose it.

## 2. Responsive Numbers
I think with a good intellisense JSDoc documentation you could cover this. So that you would have both options available and explain them in intellisense
`size={15}` resolves to `15px` 
&
`size="15px"` or `size="15%"`

## 3. Position: Relative
Not sure about the benefits of `position: static` - For me, it felt every time, that I can ignore `static` and `relative` is the better choice, because overall it's the same, but `relative` is giving you more options like `top, bottom, left, right` etc.?!

I like the idea to have the `position="relative" / "absolute"` etc. option in the `<View>` component. Maybe it could be then a good idea to cluster the Property section. And explain all the properties based on their section (e.g. Flex/Grid, positioning, Size etc.), with examples, pictures, short videos etc.
![image](https://user-images.githubusercontent.com/87228994/211012340-d9b3960b-5db0-4181-b5d8-9e59dfe1106d.png)

**Comment by blvdmitry** [comment]
Thanks for this write-up. Regarding the responsive numbers - you've used {15} that would resolve to 15px which currently resolves to 60px because we currently use number values as base unit multipliers. As someone who is familiar with Reshaped concepts, would it make sense for if number would still be (n * x1) while string would represent a literal value?

**Comment by blvdmitry** [comment]
Also just checking, I think that might depend on the actual SVG, but even though I'm adding string values support for the icon, I've tried it with style overrides in devtools and with one of our icons – it would still preserver its original ration. In the case of your dental icons, are they also supporting stretching well?
<img width="740" alt="image" src="https://user-images.githubusercontent.com/887379/211146717-2a880d9e-2dfd-402e-afbb-fef56bb562d7.png">

**Comment by mmailaender** [comment]
1. Yeah, good point - we have spacing tokens - have not considered that. But probably still, if it's explained in docs and intellisense, I think the benefit of having %, vw, vh etc. would outweigh the risk, that someone uses the field `" "` to add hard-coded px instead of the spacing tokens in `{ }`

2. Yes, the SVG is keeping his aspect ratio also while stretching.

I think as more as I'm thinking about, the main problems are really **2. Responsive Numbers** & **3. Position: Relative** combined with the base complexity of CSS, because so many different unintuitive default properties can interfere with each other... 😆 


Btw. found another thing about icon: Currently you need to pass an SVG as a component. So if I store SVGs centralized in a Bucket, I need to import the SVG as component:
`import UserIcon from "/User.svg";`

Next.js is not supporting that out of the box. So it would be great if I could also use a file path
`svg="/User.svg"`

**Comment by blvdmitry** [comment]
Done with the View PR and I've just also realised that Chakra follows the same approach for the props with numbers being used as token multiplier and string as literals. So I think there is no issues with community being unfamiliar with this approach

**Comment by blvdmitry** [comment]
Found a more or less cheap way for implementing this across the system, this syntax should work with the next release:

```
<View width={25} height={25}>
  <Icon svg={IconZap} size="100%" />
</View>
```

I'll keep this issue opened until release happens, to check with you if there is anything missing there

**Comment by blvdmitry** [comment]
@mmailaender it's out, can you check if you can achieve this now?

**Comment by mmailaender** [comment]
Is there a way to separately color `fill` & `stroke`?

If I set the SVG `fill` and `stroke` property to `currentColor` it will be both colored the same by the property `color`

`<Icon svg={RootSvg} size="100%" color="primary"/>` 

On the other side, the `style` property is not available for <Icon>
`property `style={{ stroke: "tomato", fill: "green" }}` `

**Comment by mmailaender** [comment]
Tested it now:

Scaling the SVG based on percentage values works fine - But it's important to note, that the surrounding container is `position: relative` or `position: absolute` - Because the current default is `position: static`. And with `position: static` it will not work out of the box.
```
<View width="100px" height="100px" position={"relative"}>
  <View position={"absolute"} width="100%" height="100%">
      <Icon svg={RootLeft} size="100%" />
  </View>
</View>
```


In the next step, I've put the `<AspectRatio>` in between. And here it stops working, because `<AspectRatio>` renders to a `<div>`. The `<div>` is again `position: static` by default. I can't apply `position: relative` to `<AspectRatio>`, so it breaks at this point.
```
<View width="100px" height="100px" position={"relative"}>
    <AspectRatio ratio={4 / 3}>
        <View position={"absolute"} width="100%" height="100%">
            <Icon svg={RootLeft} size="100%" />
        </View>
    </AspectRatio>
</View>
```

Again, it brings me to the point, that it feels for me, that `position: relative` is the better default value then `position: static` 🤔 😆

**Comment by blvdmitry** [comment]
I actually still want to make it default like we've discussed. Regarding your example – why would you need a position absolute here at all for the View inside?

**Comment by mmailaender** [comment]
Oh I'm sorry, missed that...

In this example having `position: absolute` has not really a benefit, but if I want to compose now multiple SVGs with each other like that:

```
<View width="100px" height="100px" position={"relative"}>
    <AspectRatio ratio={4 / 3}>
        <View position={"absolute"} width="40%" height="80%">
            <Icon svg={RootLeft} size="100%" />
        </View>
        <View position={"absolute"} width="50%" height="100%">
            <Icon svg={RootMiddle} size="100%" />
        </View>
        <View position={"absolute"} width="40%" height="80%">
            <Icon svg={RootRight} size="100%" />
        </View>
    </AspectRatio>
</View>
```


There I need `position: absolute` to remove the auto padding and to avoid outgrowing the parent.

**Comment by blvdmitry** [comment]
Got you! Was also thinking this might be the case

**Comment by blvdmitry** [comment]
Done, will be out in the next release

**Comment by mmailaender** [comment]
@blvdmitry is the new default `position: relative` only applied to `View` or also for `AspectRatio`?

**Comment by blvdmitry** [comment]
New change is only for View, but I see that AspectRatio had relative before already
