### ISSUE TITLE
[Text] Support for Fluid Typography

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#101]
Instead, having fix breaking points based on media queries, it would be great to have support for fluid typography:
https://www.smashingmagazine.com/2022/01/modern-fluid-typography-css-clamp/

**Comment by blvdmitry** [comment]
Agree, we've got this on the list for v2 since changing this might be breaking but this could also reduce the amount of tokens we ship to the bundle, which can be a really good size reduction

**Comment by blvdmitry** [comment]
I've created a new column for v2 plans on our planning board, so moving this ticket there: https://blvworkspace.notion.site/64cf1f5713344a7383330e0402f43949?v=b88a6dbbcb9a4faeb867d40d09ec0b12
