### ISSUE TITLE
Unable to publish 44 changes to team library.

### ISSUE THREAD

**Issue by salvinoto** [reshaped/community#104]
Im trying to publish the light and dark mode to my team library and I'm getting the error "Unable to publish 44 changes to team library." The components import just fine except for some broken fonts which im assuming is related to me not being able to publish the other 2 files. Any way I can fix this, I just bought it.

**Comment by salvinoto** [comment]
<img width="1343" alt="Screenshot 2023-01-06 at 6 48 03 PM" src="https://user-images.githubusercontent.com/54959187/211118330-8c14a8ba-3ec6-4168-bbb7-b975b7360d3e.png">
<img width="1920" alt="Screenshot 2023-01-06 at 6 44 24 PM" src="https://user-images.githubusercontent.com/54959187/211118343-4b10f9a7-7107-4cd8-8717-c89812591977.png">

These are some screen shots.

**Comment by blvdmitry** [comment]
Hey, thanks for creating the issue. We'll try going through your workflow using our Figma account again to see if we can reproduce the same issue

**Comment by blvdmitry** [comment]
So far it seems to work in our team license, what if you try installing the missing font? 44 styles could mean that all of them are related to typography?

https://developer.apple.com/fonts/
