### ISSUE TITLE
Button - Accessibility

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#105]
Is there a way to assign a specific shortcut to a button?
https://reshaped.so/content/docs/components/button#accessibility

So that it's getting triggered if I press e.g. 1

Something like
`<Button key="1"/>`
or
`<Button key="ctrl+1"/>`

The same for other elements like Radio, Tabs 

Use cases:

### Open search
`<TextField placeholder="Search anything..." key="ctrl+K" />`
https://reshaped.so/content/docs/components/text-field

### Shortcuts
![image](https://user-images.githubusercontent.com/87228994/211325083-42aa3623-1834-4743-bfe3-1fabb856f58b.png)
`<Button key="1"/>`
https://reshaped.so/content/docs/components/button

### Switching Tabs
![image](https://user-images.githubusercontent.com/87228994/211325652-c0c1f4b4-ba23-4295-b309-1b1af1eecdd6.png)
```
<Tabs>
  <Tabs.List>
    <Tabs.Item value="0" key="ctrl+1">App 1</Tabs.Item>
    <Tabs.Item value="1" key="ctrl+2">App 2</Tabs.Item>
  </Tabs.List>
</Tabs>
```

Mantine has created a hook for this:
https://mantine.dev/hooks/use-hotkeys/

**Comment by blvdmitry** [comment]
Even before I read the whole message up to the Mantine link,  I was about to ask – do you think you need key propery on the Actionable and components using it or should it just be a hook, since sometimes you don't want to click a button and trigger its onClick handler, but just call the same method when shortcut is pressed.

```tsx
// Single shortcut
useHotkey("ctrl + 1", onClick);

// Multiple shortcuts
useHotkey(["ctrl + k", "/"], focusSearch);

// Trigger only when interacting with specific elements
const useHotkey("ctrl + Enter", handleSubmit, inputRef);
```

**Comment by mmailaender** [comment]
I think a hook is more flexible, although the learning curve is a bit higher than compared to a simple prop. So with a great explanation/presentation in the docs, the hook could be the smarter way to go.

**Comment by blvdmitry** [comment]
This took some time but I have a working version of the hook after a few iterations on it. It provides the following:

```jsx
// Single hotkey
useHotkeys({ "b": callback });

// Multiple keys for the same callback
useHotkeys({ "b, c": callback });

// Multiple callbacks
useHotkeys({ "b": callback1, "c": callback2 });

// Key combinations
useHotkeys({ "b + c": callback });

// Assigning to components
const { ref } = useHotkeys({ "b": callback });

<Button attributes={{ ref }} />

// Checking what's currently pressed
const { checkHotkeyState } = useHotkeys({ "b+c": callback });

checkHotkeyState("b+c");
checkHotkeyState("b");
checkHotkeyState("a"); // works with any hotkey you pass to it
```

Anything you would need on top of that for the case you're solving right now or will it already be helpful already? I have a few improvement ideas but wanted to make sure we can ship its first version now and focus on the rest of the created tickets for the release

**Comment by mmailaender** [comment]
One question:

// Checking what's currently pressed
const { checkHotkeyState } = useHotkeys({ "b+c": callback });

checkHotkeyState("b+c");
checkHotkeyState("b");
checkHotkeyState("a"); // works with any hotkey you pass to it

why do I need to pass a value to check what's currently pressed?

---

// Assigning to components
const { ref } = useHotkeys({ "b": callback });

<Button attributes={{ ref }} />

Means that, the hotkey will only work in the context of the button? e.g. I navigate with `tab` to `Button` and then pressing `b`?

**Comment by blvdmitry** [comment]
1. Main reason for that was to make sure you can check the state not just for the whole hotkey combination, but also for individual key presses. That could be useful to display the intermediate state. Visual example: https://twitter.com/blvdmitry/status/1615112276302004224

2. Yes, same as an example in Mantine, where you might want to assign a hotkey only when you're within a form to send the message in the chat. Or when you've selected an element and want to move it with your keyboard.

**Comment by mmailaender** [comment]
Great - looking forward to the release

**Comment by blvdmitry** [comment]
Thanks for the help, closing the issue then, as it's been merged now
