### ISSUE TITLE
[Documentation] Installation - SSR leads to 404

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#112]
https://reshaped.so/content/docs/hooks/use-theme

Clicking on the link `Installation - SSR` leads to a 404

![Screenshot_20230115-093411.png](https://user-images.githubusercontent.com/87228994/212531105-357d9b35-def9-4cca-8dc5-431b194cf23e.png)

**Comment by blvdmitry** [comment]
Thanks for noticing, fixed it locally, going to roll this out before the next release
