### ISSUE TITLE
Is Dismissible working properly? 

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#113]
If I understand `<Dismissible>` correctly, it means that if I click on the `X` all the content that is wrapped inside `<Dismissible>` should disappear. Is that right? 

Because if yes, the component in the documentation is not working properly on mobile (not tested yet on PC). If I click on the `X` nothing happens

https://reshaped.so/content/docs/utilities/dismissible

**Comment by blvdmitry** [comment]
Yes, that's expected. It only triggers onClose to then let you connect it with the logic you need. For example you might want to close its parent modal when x is clicked and not actually dismiss anything inside the Dismissible

**Comment by mmailaender** [comment]
@blvdmitry you mean e.g. a modal? Maybe you want to elevate the example in the docs, so the users have a working example :)

**Comment by blvdmitry** [comment]
Just checked the docs again, going to update them to make it easier to understand

**Comment by blvdmitry** [comment]
Updated the docs with a dismissible card example and removed the composition section completely since it didn't make much sense anymore. Merged for the next release.
