### ISSUE TITLE
[Docs] 'use client' directive - Next.js

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#116]
You should add to the code snippet in the documentation the `'use client'` snippet. Without it, reshaped will not work in React 13 App directory.
https://reshaped.so/content/docs/getting-started/integrations/next/next-13#start-using-reshaped-components

Alternatively, the user can wrap the whole reshaped components and export it (Better approach, because then he can use the components together with server only components):

```
'use client';

export * from "reshaped";
```

**Comment by blvdmitry** [comment]
Partially duplicates https://github.com/reshaped/community/issues/89

Going to keep track of this in that issue
