### ISSUE TITLE
CSR & SSR Badge

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#121]
Big benefit of all Tailwind CSS components. They support CSR (Client-side-render) and SSR out of the box.
Atm I think the most, if not all components from Reshaped are CSR only. If you bring in the future stronger SSR support, it would be great to have some indicator what component renders in which context.
![image](https://user-images.githubusercontent.com/87228994/213906129-b0351abb-4449-4f7b-a401-cbe2b414b6f4.png)

Btw. not sure since then it's there. But Chrome developer tools have now a really nice way of showcasing CSS Flex options: 
![image](https://user-images.githubusercontent.com/87228994/213906078-a58c811a-6f85-48a8-a3dd-ee0c1914a981.png)

**Comment by blvdmitry** [comment]
We don't mark components as CSR / SSR since all components support SSR out of the box. I think it might be confusing because of the "use client" in them, but that's only temporary because of the context issues with React Server Components beta in Next.js. 

Important note here would be that SSR is not the same as RSC, even if we keep "use client" only for some of the components, that still means that all our components don't break during SSR.

**Comment by mmailaender** [comment]
Eventually I'm missing here the main problem. So with Nextjs 13 SSR was introduced as default inside the App directory. So every code will be rendered on the server, except I put the `use client` directive at the top of the file. Then the file will be rendered client side. 
If I leave the `use client` directive away, the Reshaped components throwing errors. So I thought, that this is a problem with Reshaped an SSR. But you say it's not a SSR problem, instead it's some context issue(Bug?)?

**Comment by blvdmitry** [comment]
I think there is a bit of confusion here.
Next.js introduced support for React Server Components (RSC) which is the beta feature available in React. It enables dropping some components completely from the client-side JS bundle and ignoring their React hydration completely. It gets enabled in Next.js when "use client" is not used and is the feature that doesn't work well with React context being present in the bundle in the dev mode.

Server side rendering (SSR) is a feature that's been in Next.js and other frameworks for a long time, which renders React on server to make sure that you have HTML rendered even before JS bundle is downloaded and executed on the client. This means that components render function should not be using any of the DOM apis while rendering in NodeJS happens. It's fully supported in all components.

**Comment by mmailaender** [comment]
Ah, now that makes sense. Thank you for that awesome explanation! :)
