### ISSUE TITLE
Theming plugin

### ISSUE THREAD

**Issue by blvdmitry** [reshaped/community#20]
Find or create a plugin for switching themes in FIgma

**Comment by mmailaender** [comment]
We're using https://www.figma.com/community/plugin/843461159747178978/Figma-Tokens for this

https://docs.figmatokens.com/token-sets

**Comment by blvdmitry** [comment]
Definitely looking into the plugins available in the community for this but also since we have a bit more context about how tokens are used in the theme we plan to support additional features like color contrast validations

**Comment by mmailaender** [comment]
Maybe opening a request there? https://github.com/six7/figma-tokens I know that these guys are pretty fast pushing updates. At least midterm maybe a good option, instead of developing a whole new Figma app by your own :)

**Comment by blvdmitry** [comment]
We've checked Figma tokens and it seems like theme grouping is going to be a part of the pro version. In our case we would like to not add any additional purchase requirements for our customers, so we've split theming implementation into multiple steps. 

As the first step, we are going to implement theme importing from our theme template, which will allow us to support theme exports to React and dynamic theme switching in Figma. We've also planned the first release for v1.3 according to our roadmap: https://blvworkspace.notion.site/64cf1f5713344a7383330e0402f43949?v=b88a6dbbcb9a4faeb867d40d09ec0b12

In the next steps, we'll be updating it to a theme editor right in Figma with a theme template being exported from the plugin, support for custom tokens not supported in Figma, theme accessibility validation, and remote JSON storage support. Once we're comfortable with the quality we're also considering making it free for everyone.

**Comment by blvdmitry** [comment]
The first version of our plugin is live, so I'm closing this issue but keeping the one around the export since it's going to be one of our next steps 

https://reshaped.so/figma-plugin
