### ISSUE TITLE
Dark Mode in Figma Fails

### ISSUE THREAD

**Issue by jamesstoneco** [reshaped/community#61]
I have tried many times using the themer plugin to add the dark and light styles and to change them and it has no effect. Additionally, creating a new figma file with only the dark mode library, for styles, also results in light mode components.

I am using the latest version of Arcade, latest version of Figma, latest version of the themer plugin.

The only way to change components to dark mode, is to individually change each style to the dark mode style, which is slow and tedious.

**Comment by oleksiidrozdenko** [comment]
Hi James, thanks for reporting!
I've just tested the Themer plugin and [it worked well in the browser](https://drive.google.com/file/d/1xRDxht4UhUPBXLOFis9Fzc3QxvyxtnEA/view?usp=sharing), yet failed to load in the Figma app, so looks like a plugin's bug. Can you please share details of your setup:
- Browser or app?
- When you open jsonbin and view bin's details, do you see references to arcade libraries? 

Thank you!

**Comment by oleksiidrozdenko** [comment]
Hi @jamesstoneco!

Checking if you managed to make Themer work. 
Alternatively, you can also swap light and dark mode libraries using the [native Figma feature](https://help.figma.com/hc/en-us/articles/4404856784663-Swap-style-and-component-libraries).

Let me know if that works for you. Thanks and happy holidays!
