### ISSUE TITLE
support for Positive buttons

### ISSUE THREAD

**Issue by elenerandarill** [reshaped/community#62]
Since color Positive is used for Badges and Avatars why it cannot be used for Buttons also? It seems to be the only color with this case, the rest is being used everywhere :)

**Comment by blvdmitry** [comment]
Makes sense!
Going to add it for the next release, we have it planned around the end of this week

**Comment by blvdmitry** [comment]
It's ready. We're going to publish it in React library for you by tomorrow and the Figma library will follow by the beginning of the next week. Thanks for the request!
