### ISSUE TITLE
end icon slot

### ISSUE THREAD

**Issue by elenerandarill** [reshaped/community#63]
In your documentation you have greatly prepared using `icon` instead of `startSlot` inside a `TextField`. 
It is a nice and clean solution <3.
I am lacking the same for `endSlot` being replaceable with ...maybe `endIcon`? 
I have seen in Figma that there are examples of using both start and end icons within TextField.
I could only achieve the same by using
`endSlot: (<Icon svg={zapIcon} size={4} />)` 
Do you think it could be done in similar matter? :)

**Comment by blvdmitry** [comment]
I think that would be a nice addition to the API but I'm also curious to learn more about your use case. Do you plan to use it for a decorative icon on the end side or do you want to make that icon clickable as well to make it work as for example a "clear" action?

**Comment by elenerandarill** [comment]
Actually I think both options would be great to have and useful - I am creating storybook with your components for a client and his needs might change over time, so I try to think of various usecases :) And since it was in your Figma as an example, them you must have thought about it also, right? :D

**Comment by blvdmitry** [comment]
Absolutely. By the way, in that example, do you need two icons displayed at the same time? I was thinking that in Button component we already have an `iconPosition` property, so might be a good thing to keep the API consistent here as well

**Comment by blvdmitry** [comment]
Implemented it for the next release :)
