### ISSUE TITLE
Elevated Tokens

### ISSUE THREAD

**Issue by bohdank1995** [reshaped/community#66]
Hello,
In our product, we have dark elevated objects. For example dropdowns have a dark background. But what if the elevated object has multiple elevation layers? I've decided to use elevated-2 token (for Gray 90 from the picture below ([carbon design](https://carbondesignsystem.com/guidelines/color/overview/))). But I'm not 100% sure about this solution. How should I name tokens, in this case, to stay in the sematic color structure? 

Maybe you also want to add some more lines in your documentation, to make it for other people easier that are coming after me 
https://reshaped.so/content/docs/tokens/color#elevation-colors

<img width="509" alt="Screenshot 2022-05-31 at 14 25 43" src="https://user-images.githubusercontent.com/104136805/171162720-8a428fb7-8686-413e-9554-14144c97a555.png">

**Comment by blvdmitry** [comment]
Hey, that's a great point. Originally we decided to chase simplicity here and implemented only `page` -> `base` -> `elevated` tokens to cover most of the elevation cases. That might be suboptimal in case there is something elevated even more inside dropdowns but we were struggling to find a common case like this. Do you have an example of a similar product case to share? 

Speaking generally though, I guess elevated-2 added on top of elevated sounds well aligned with the approach we use in typography.

**Comment by bohdank1995** [comment]
For example, it can be a popover for creating an event. There is a header that has a higher surface elevation. 

<img width="462" alt="Screenshot 2022-06-01 at 12 48 01" src="https://user-images.githubusercontent.com/104136805/171376992-c5d7a153-231e-4c44-b8b1-0a44643767f5.png">

**Comment by blvdmitry** [comment]
Thanks, got to think about this one. 
I guess for this specific example also it might also be `background-neutral-faded` used which will have enough contrast in both modes and won't require an additional shadow in light mode, since all elevated color tokens are white in light mode.

**Comment by bohdank1995** [comment]
Got it, thank you for clarification😊
