### ISSUE TITLE
Need invoice for purchase

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#67]
Hi,
it seems there was no invoice sent to me after completing the purchase. How can I get it?

**Comment by blvdmitry** [comment]
Hey, our Stripe setup should send a payment confirmation email after the purchase. If you need a separate invoice or haven’t received the original email - I can generate an invoice for you manually.

**Comment by mmailaender** [comment]
Yes, it was this HTML page - I have converted it now to PDF - I think it should be enough.
