### ISSUE TITLE
Remix React installation guide!

### ISSUE THREAD

**Issue by NadimHallaq** [reshaped/community#69]
I'm using React Remix [https://remix.run/](url) its a server side react framework but it does not use Webpack, it uses Vite, I tried getting it to work, first got the "export is not defined", fixed it with importing the serverDependenciesToBundle in remix .config [docs link](https://remix.run/docs/en/v1/api/conventions#serverdependenciestobundle) and got the app to run, but no styles at all.
I tried setting up postcss [docs link](https://remix.run/docs/en/v1/guides/styling#postcss) but I don't think thats the solution either.

Can anyone make a Remix starter, or guide me to how I can get it working!

**Comment by blvdmitry** [comment]
Hey, let me try to set it up today and see how it goes. I remember I had issues with Remix in the past due to how they work with CSS but we've published Reshaped bundles to the package as single css and js files so it might be solved automatically now with a correct setup.

**Comment by blvdmitry** [comment]
Went quite straightforward actually, made it work in 15 minutes with no prior Remix experience:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/887379/173229642-869f7a92-7fb8-4eeb-93ad-d19f4773bc19.png">

Going to align it with other examples and push it later to this repo. Documentation on the website will be available starting with our next release. Meanwhile, here is what I ended up with in my route file:

```
import { Button, Frame, Reshaped } from "reshaped/bundle";
import styles from "reshaped/bundle.css";
import theme from "reshaped/themes/reshaped/theme.css";

export default function Index() {
  return (
    <Reshaped theme="reshaped">
      <Frame padding={4}>
        <Button color="primary">Reshaped button</Button>
      </Frame>
    </Reshaped>
  );
}

export function links() {
  return [
    { rel: "stylesheet", href: styles },
    { rel: "stylesheet", href: theme },
  ];
}
```

Note that all CSS imports and Reshaped provider should be stored in the application wrapper and not in every route

**Comment by blvdmitry** [comment]
Here is the repo link: https://github.com/reshaped/community/tree/master/examples/remix-starter
I'll close the issue now, you can expect the guideline to be published with the next release, which should happen early next week.

**Comment by NadimHallaq** [comment]
True, I got it working, I think the part the tripped me was the `import { Button } from "reshaped";` compared to `import { Button } from "reshaped/bundle";`.  But anyways, thank you for the fast solution, appreciate it :)

**Comment by blvdmitry** [comment]
Yeah, it's always tempting to just import things from "reshaped". The builds are different, the default one is ESM with CSS imports left in the code. But at least it throws an error when you import the wrong one with Remix instead of silently failing
