### ISSUE TITLE
Document limitations of Alias

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#72]
https://reshaped.so/content/docs/components/dropdown-menu

You saying here:

DropdownMenu.Item is an alias for the MenuItem component that integrates with the DropdownMenu functionality. **It still supports most of the properties MenuItem supports.**

**DropdownMenu supports most of the properties Popover doe**s, which means you can use its event handlers or position it differently.

--> "support most of the properties" implies for me that there are properties, that are not supported. It would be great, if you could document those limitations.

**Comment by blvdmitry** [comment]
Hey, that's a good point. Maybe `proxy` or a similar naming is a better way to describe it? DropdownMenu.Item is using MenuItem but has a few of its properties predefined to provide a consistent UX and behavior of the component. I'm adding more specific on which properties are predefined and which are not and will release it later today.

**Comment by blvdmitry** [comment]
The updated properties list is now live in the docs, let me know if this makes more sense now. I'm still using the word alias though for now.

**Comment by mmailaender** [comment]
Definitly an improvements. Still it's flowtext. What do you think about something like that? 

# Alias
Alias are predefined base components for a better usage inside other components. 

| Alias | Base component | Predefined properties | 
| ----------- | ----------- | ----------- | 
| DropdownMenu.Item | MenuItem | className, size, roundedCorners |

**Comment by blvdmitry** [comment]
This makes me think if it was a good idea at all to mention that it's an alias since using MenuItem directly there might unexpectedly break something. For example, DropdownMenu.Item might have access to DropdownMenu specific context, while MenuItem won't have it. Maybe it's worth just listing all supported properties in DropdownMenu.Item instead of the one we omit?

**Comment by mmailaender** [comment]
Or maybe you could stronger push the idea of composed components and maybe finding a good way to reduce unexpected breaks? 
Because I can say at least for me, knowing that DropdownMenu.Item is an alias of MenuItem reduces some complexity in my mind.
DropdownMenu.Item is not another component (as more individuell components as more complex it will get). So my knowledge about MenuItem is also valid here.

**Comment by blvdmitry** [comment]
That makes sense, I'll go through it once more

**Comment by blvdmitry** [comment]
Updated for the next release
