### ISSUE TITLE
Configurator Summary at the top of every Component

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#74]
I find myself often searching for something and try to find the relevant part of the documentation. In the current approach, I have to scroll through text. I'm missing an overview section at the top of the component, that works maybe like a configurator, where I can select/unselect different props and based on that, the component will be visualized and the code displayed. (Like a compressed view of the whole component description)

### Example Radio

- [ ] checked
- [ ] defaultChecked
- [ ] disable
- [ ] hasError
- [ ] ...

< Visualization of Component >

< Code >

< Property explanation >

Other topic:

![image](https://user-images.githubusercontent.com/87228994/191688858-99e2d416-45b9-4a6e-af69-d8adcee78198.png)

It would be great, if you could replace the purple tick with unique icons - So the cognitive load is reduced if e.g. a component support responsive size values - I only see the icon, and I'm aware - I don't need to read the text

**Comment by blvdmitry** [comment]
Hey, that's a good idea and we were thinking about general updates to the documentation as well, including current docs, separate tab for the properties and some sort of compressed value proposition for the component (not just about the props but also about the edge cases component is solving).

**Comment by blvdmitry** [comment]
Now that I read it again, I also forgot to mention that I like how Material docs have these interactive demos you're talking about: https://material.io/components/buttons#usage

However, it either becomes very complicated if we display all the properties in it, or it shows only a part of the cases. So I would check if splitting component API into a separate tab + adding a live editor for the components helps. Do you think it should make documentation scanning easier for you?

**Comment by mmailaender** [comment]
Yes, material is doing that really nicely with the configurator. I like that. 
Are you talking about something like that?
![image](https://user-images.githubusercontent.com/87228994/192132677-04dc6929-f35f-42a4-b542-6f685b6904e7.png)

And putting into Live Preview the Interactive demo?


I also like their "Theming" section. Maybe it could be more compressed, and the theming code could be more easily to access.

**Comment by mmailaender** [comment]
That's cool: https://mantine.dev/core/slider/

**Comment by blvdmitry** [comment]
Agree, I think it's always a thing about which properties should exist in this demo part or if we can somehow provide full controls for the component there without making it look too complex

**Comment by blvdmitry** [comment]
@mmailaender considering that we might move "highlights" to a separate tab to talk about the value proposition of the component for people who need to understand what it solves for them; do you think it you would like an approach where we would just display "keywords" for the component, including it supporting responsive props? I think responsive props is the only real feature that can be highlighted consistently (as we also do that in the props table)

**Comment by blvdmitry** [comment]
Thinking about something like this:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/887379/192626481-762104fb-d087-4896-aade-7c823ae5808b.png">

- Condensed intro section grouped together
- Additional link to the storybook setup of the component
- Tabs for immediate access to properties
- Settings button (ignore the icons for now) that opens a drawer inside the demo with "core" properties of the component and a few global settings like RTL, color mode, theme. All are scoped by the demo box.

**Comment by mmailaender** [comment]
I think the screenshot that you shared is a pretty good step forward. (About storybook and Keywords I'm not sure if it's needed to be so prominent - except maybe the responsive tag - but I hope also that is in the future valid for all components, so then again you don't need it probably so prominent)

Some self-reflection:
My Team and I played the last days around with Mantine, Chakra, and Reshaped and Mantine was super easy to start because of the configurator. But at the point the configurator was stopping, it was getting a lot slower to understand the component for the non Frontend geeks.

I see two reasons for that:
1. Limitation of configurator
2. The property sections misses examples and the description are really compressed, so if you're not yet familiar with that stuff it slows you down
![image](https://user-images.githubusercontent.com/87228994/192717480-966c7c73-a32d-48cc-878d-80cd13ae1906.png)
https://mantine.dev/core/grid/

So I have the feeling that the following points would really help (especially for not so experienced user) to get really easy into it:
1. Configurator with almost all props
2. Property description with Summary, **Explanation** and **Example**
3. Theming and Styling section (Chakra has such a section, but it's nothing written there... https://chakra-ui.com/docs/components/accordion/theming)
4. Examples, how and for what I can use that component (Including code example). (I see that on your screen - like it :))

**Comment by blvdmitry** [comment]
Top section is now live with examples available for one component: https://reshaped.so/content/docs/components/action-bar

Interactive preview and more examples are planned for the next release, thanks for giving us a heads-up about this!

**Comment by blvdmitry** [comment]
This has actually kicked off and I'm building a full-featured property panel now, using the same data to power the property controls and the props table in the docs. Core functionality is done now, so I'm mostly adding support for various data types now and will be moving all components docs to the new data format afterwards.

**Comment by blvdmitry** [comment]
Going to be live in the next release, all components docs are updated now
![image](https://user-images.githubusercontent.com/887379/201524535-d9c746c3-87b2-429b-b00e-6a82141164df.png)

**Comment by blvdmitry** [comment]
It's live now, for example here's the Button component link:  https://reshaped.so/content/docs/components/button
