### ISSUE TITLE
How can I upgrade the Reshaped Figma component file?

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#75]
I'm using Reshaped Figma components as library in Figma. If I import the 1.6 it will be created as a new file in Figma. Instead, I would like to update the existing ones, so that the library stays intact. Do I need to copy the new elements over, or is there a better approach?

**Comment by blvdmitry** [comment]
One we recommend right now, while Figma doesn't have another approach is to use library swapping. We outline the process here: https://reshaped.so/content/docs/getting-started/figma/libraries#update-library-version

**Comment by mmailaender** [comment]
That solves it for now - thx :)

You have here some duplicated text :)
![image](https://user-images.githubusercontent.com/87228994/192162302-c24d60d4-244a-4748-9f17-fce2783ba5be.png)

**Comment by blvdmitry** [comment]
Thanks, I removed it and will include it in the next deployment
