### ISSUE TITLE
Accordion component

### ISSUE THREAD

**Issue by blvdmitry** [reshaped/community#76]
Based on the received request, I'm creating the ticket here as well. We need to implement the collapsible / accordion functionality. We already have a similar example using Framer Motion on our website that can be used as a reference: https://reshaped.so/faq

Examples from other libraries:
MUI https://mui.com/material-ui/react-accordion/
Chakra https://chakra-ui.com/docs/components/accordion/usage

Notion ticket: https://blvworkspace.notion.site/Accordion-component-3afd5f6e3b4a480b899f5588884b9f65

**Comment by mmailaender** [comment]
Quite good documentation of an accordion component: https://mantine.dev/core/accordion/

**Comment by blvdmitry** [comment]
I got the first draft ready today and made a quite custom example of how it can be used: https://twitter.com/blvdmitry/status/1582826325328334850

Compared to other accordion implementations, I'm avoiding hardcoding layout styles into it since we prefer composition over style overrides in Reshaped to avoid style collisions. The main challenge with that is handling the gap between the trigger and the content. When using View, the gap should be enabled only when the accordion is active, and it should be animated. 

The best solution for that is to just add top padding to the content wrapper, and it's possible to achieve with custom styles already. However, it would be a better experience to add individual padding support to the View utility instead of writing custom styles every single time, so I will work on that improvement together with the Accordion release.

**Comment by blvdmitry** [comment]
The component is ready now, waiting for the release 
https://twitter.com/blvdmitry/status/1583729872270155776
