### ISSUE TITLE
Docker with local npm package

### ISSUE THREAD

**Issue by NadimHallaq** [reshaped/community#80]
I'm trying to build my docker image, but I'm getting this error from npm because reshaped is a local package, so the npm step always throws this error "no such file or directory, open '/vendor/reshapedv1.8.tgz'". 

Running locally works fine, the docker image is the only problem :((

I new to docker in general so if anyone has a solution of how to handle local packages with docker please let me know! 

A little info, 
-I'm using Remix, the reshaped example references the reshaped files with ../../vendor/reshaped  this gets changed automatically once I run npm install reshaped to file:vendor/reshapedv1.8.tgz

-my docker file is very simple:
FROM node:16-bullseye-slim as base
WORKDIR /app
COPY package.json ./
RUN npm install 
COPY . . 
EXPOSE 4000
CMD ["npm", "start"]

-the vendor reshaped file is at the root path of my project
/app
/public
/vendor/reshapedv1.8.tgz
/Dockerfile
etc.....

**Comment by blvdmitry** [comment]
Hey, might this because of how docker container is set up? I see you pick /app as a working directory and copy package.json inside. Shouldn't either storing vendor inside the app folder in this case or keeping its parent folder as a working directory?

**Comment by NadimHallaq** [comment]
I think the workdir /app has nothing to do with the original /app its only used to make it easier for me to reference files inside my Dockerfile. 

I did try it though, I moved the vendor folder inside the /app and I still get the same error, 
`npm WARN tarball tarball data for reshaped@file:app/vendor/reshapedv1.8.tgz (null) seems to be corrupted. Trying again.`
`no such file or directory, open '/app/app/vendor/reshapedv1.8.tgz'`

**Comment by NadimHallaq** [comment]
Just in case someone faces the same issue! 

I did copy . /app (my workdir) and it all worked fine. 

and added a .dockerignore file to make sure that my image stays small
ie: 
/node_modules
*.log
.DS_Store
.env
/.cache
/public/build
/build

I still have no idea what I'm doing with docker beyond some basic commands but it worked

Hope this helps
