### ISSUE TITLE
Focus problem with TextField and TextArea

### ISSUE THREAD

**Issue by NadimHallaq** [reshaped/community#81]
When I change the input type to number the focus is displayed twice once in my primary color and once with the blue. Same issue with textArea but in that case I change nothing, I just use the default settings. 
Example of TextField:

```
  <TextField
              startSlot={<Badge color="primary">pageCount</Badge>}
              name="pageNumbers"
              inputAttributes={{
                type: "number",
                autoComplete: "off",
              }}
            />
```
```
    <FormControl>
          <FormControl.Label>Email</FormControl.Label>
          <TextArea name="name" placeholder="example@gmail.com" />
        </FormControl>
```

<img width="1438" alt="Screen Shot 2022-11-29 at 4 36 02 PM" src="https://user-images.githubusercontent.com/54821370/204654906-f8809cdc-96d6-4e21-ba7e-299abf12c13f.png">
<img width="1576" alt="Screen Shot 2022-11-29 at 4 46 51 PM" src="https://user-images.githubusercontent.com/54821370/204655131-a645d3c8-0ba0-4241-b076-a2ce90fa2f84.png">

**Comment by blvdmitry** [comment]
Can you share which browser that is? Also do I get it right that red focus is coming from Reshaped with primary color themed as red and the other comes from a native focus?

**Comment by NadimHallaq** [comment]
Safari Version 15.6 and Chrome Version 107.0.5304.110 both have it!

Yeah, it supposed to be orange lol, orange is from reshaped and blue is browser focus. Only happens on those tow, Default Textfield has just the orange focus

**Comment by blvdmitry** [comment]
Interesting, can't reproduce it locally: 
<img width="349" alt="image" src="https://user-images.githubusercontent.com/887379/204678651-c6d4af5d-234a-4c86-a7ac-e1636953485e.png">

Can you confirm that this outline is coming from the default input styles and not from some additional reset that has more specificity?

**Comment by NadimHallaq** [comment]
Yes, I'm also using tailwind, maybe thats the problem then? 

Should I just set all the tailwind focus styles to none?

**Comment by blvdmitry** [comment]
Ah, makes sense, Tailwind indeed comes with a default outline. Maybe you can try following this answer and remove outline from the tags like `button, input, textarea` since you're anyways getting them from Reshaped, where we apply it through box-shadow

**Comment by NadimHallaq** [comment]
Fixed, I did not have to reset the outline, I had imported the tailwind form Plugin and once I removed that everything went back to normal.

Now i just need to reactor the rest of the inputs and textareas to use reshaped. 

Thank you a lot!
