### ISSUE TITLE
Question Around Breakpoints

### ISSUE THREAD

**Issue by TatisLois** [reshaped/community#82]
Hey!

I was curious on the best way to find the supported breakpoints for certain components like `Text`. 

**Context**

Building a remix application and using Text, Container, View components for layout on desktop it's two 6 col grid elements but on mobile I'd like it to break to 12. 

I don't think there is native way to do this in reshaped such as a "use breakpoint" hook or API in the props similar to tailwind. So I believe I have to roll it out myself and want to make sure the values match. Thank you!

**Comment by blvdmitry** [comment]
Hey, breaking this down into 2 answers:
- Layout related in all of our components support responsive syntax to make sure it can be changed based on the viewport even during SSR. For example, for View there is a separate Responsive properties section: https://reshaped.so/content/docs/utilities/view#responsive-properties
- Text is size automatically changes based on the theme definitions, which you can change in the reshaped.config.js file: https://reshaped.so/content/docs/theming/creating-themes

If you think there is some other functionality you will need that I haven't mentioned – please let us know

**Comment by TatisLois** [comment]
I missed the responsive section, darn! I searched for breakpoint(s) and media query. I need to improve my ChatGPT skills. Thank you again, this is perfect.

**Comment by blvdmitry** [comment]
Good point, maybe we can improve the title of these sections
