### ISSUE TITLE
JSX live

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#85]
I like the new configurator, that I can play arround with all options, and See directly a physical Feedback. 

Nice to have: That the code block is also editable, so I could add some elements by myself to play a bit more. Chakra has that, and I think it's pretty cool

![Screenshot_20221209-220006.png](https://user-images.githubusercontent.com/87228994/206795613-fa7a12d9-825b-4e6c-a618-7479db8c1c9c.png)

**Comment by blvdmitry** [comment]
https://user-images.githubusercontent.com/887379/206877042-50cf6b66-67a4-401d-9c61-f22036e8dd4b.mov

Luckily react-live supports it already, so I've just enabled it for the next release with some minor tweaks

**Comment by blvdmitry** [comment]
It's live :)
