### ISSUE TITLE
Explain use of properties in property tab

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#86]
Maybe not more so important after the dynamic component configurator, but I think it would polish the doc and could explain for newbies better some of the props.

**Comment by mmailaender** [comment]
I really like the explainations and visualizations from https://css-tricks.com/snippets/css/a-guide-to-flexbox/ maybe this one could be brocken up into pices and added to the single property explanation. This would be pretty unique and probably quite helpful for beginner. I also learned with that Page Flex and their properties some time ago quite easily 😉

**Comment by blvdmitry** [comment]
Instead of trying to implement the same docs, do you think it would be helpful to add some sort of a highlight section linking to this article? I think I've used it as well a very long time ago to see how flex works :)

**Comment by mmailaender** [comment]
I think you're not following the same terminology - it's more like an abstraction from Flex, so it could be maybe a bit confusing.

So doing the mapping for the user could be probably helpful for the one who knows flex etc. and for the newbie. I had something like that in mind (Working with Accordions):
![image](https://user-images.githubusercontent.com/87228994/206908798-6534e437-d021-4a76-a45a-e5820013285c.png)




Btw. I have a horizontal scroll wheel at the bottom (2560 x 1440)
![image](https://user-images.githubusercontent.com/87228994/206906306-cd686e8a-7251-41e0-9ee0-0fdd5098810c.png)

And the dropdown has white on white in the control section
![image](https://user-images.githubusercontent.com/87228994/206906664-432bd880-7e7a-411e-b613-5743acc9163a.png)

**Comment by blvdmitry** [comment]
1. I think I agree with your idea, considering that View is one of the most fundamental components of Reshaped
2. Fixed the scrolling, thanks for the heads-up, going to be live with the next roll-out
3. Interesting, which browser is that? This should be native select, so I assume browser/OS doesn't handle it automatically but probably we can do something about it

**Comment by mmailaender** [comment]
Using Chrome Version 108.0.5359.99 tested it on my Laptop and PC. On both the color Bug appears if I have selected dark theme

**Comment by blvdmitry** [comment]
Is this windows? Also any plugins that might be customizing this behavior? I assume the same happens for the Select component in general?

**Comment by blvdmitry** [comment]
It does depend on the OS, this is what I see on Windows in Edge as well, going to look further into this issue

<img width="403" alt="image" src="https://user-images.githubusercontent.com/887379/208772331-c7d52a15-313b-4f9b-959a-45bc5fb329a7.png">

**Comment by blvdmitry** [comment]
Solved, shipping in the next release. Only originally reported requests is left now

**Comment by blvdmitry** [comment]
For the View docs, we'll start with the grouped properties and an interactive playground with a link to a flexbox guide, let's see how that works :) 

https://twitter.com/blvdmitry/status/1613646771854483456

**Comment by mmailaender** [comment]
@blvdmitry great Job - This feels already so much easier to grasp - and it's great to see that it gets quite good Feedback on Twitter, too 🚀
Motivates also me to share more Feedback 🥳🙂
