### ISSUE TITLE
Improve Figma Structure

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#88]
Currently behavior

1. Click on the library in Figma and I see 
![image](https://user-images.githubusercontent.com/87228994/206864893-fcffb1da-5c4f-44f8-b6b1-1879d09b1635.png)
2. Clicking on Components and waiting 5 seconds until it's opens
![image](https://user-images.githubusercontent.com/87228994/206864926-c4362c27-9166-4ed3-85c6-3fb07987b4b4.png)
3. Clicking on layout to see the available components
![image](https://user-images.githubusercontent.com/87228994/206864942-621bbd82-fcea-4a96-ba1c-d7576e45e72d.png)
4. I want to see e.g. the badge, so I click on it to see where it is 
![image](https://user-images.githubusercontent.com/87228994/206864966-53daf7c7-18b6-444c-8329-347879d6fd1f.png)
5. Now I have to zoom in to work with it.

---

I think this process could be shortened a lot, by splitting up the components on page level
![image](https://user-images.githubusercontent.com/87228994/206865009-ed6b8c2d-0eba-4e6d-a19e-82ba7fca8874.png)
Then I would select directly the component that is interesting for me on page level. The loading time from step 2 would be faster, because he doesn't need to load all components. I could save the click from step 3 and the zoom from step 5.

**Comment by blvdmitry** [comment]
Added this to our backlog for the next release

**Comment by blvdmitry** [comment]
All ready for the next release, closing the ticket meanwhile :) 
<img width="403" alt="image" src="https://user-images.githubusercontent.com/887379/208770995-313a9f1c-dffa-431b-a0ce-877ee2bde1a7.png">
