### ISSUE TITLE
1 Million UI libraries - Why are you existing?

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#95]
## Hero shot:
![image](https://user-images.githubusercontent.com/87228994/209197005-e2dc4f85-9d76-475d-90a7-5937fd91f349.png)

![image](https://user-images.githubusercontent.com/87228994/209197050-9d3af366-4545-45a6-aebf-43f4a781b052.png)

![image](https://user-images.githubusercontent.com/87228994/209197116-aea838b1-bee2-49fd-982e-f0a641e5bf32.png)

etc...

If I visit these pages, I'm asking myself: Why are you creating now also another UI library? And especially for Reshaped: And why a paid one? MUI, Chakra, Mantine have all a generous free tiers....
To rephrase it: I think you have some potential to show why it's worth to pay you some money ;)

My points, why I like reshaped:

1. On a good way to have the cleanest and clearest documentation from all -> Fast adoption
2. Native design token support
3. Simplified theming with e.g. semantic colors
4. Easy theming plugin for Figma (Github export missing)
5. Powerful and flexible concept with Accordion & View (Not yet consistent for all components)

Maybe you can think about a way, that the user is understanding clear in 10 to 20 seconds, why he needs you. Maybe a GIF that is showing the process in fast mode?

**Comment by blvdmitry** [comment]
Yeah, that's interesting. We have a 3-minute demo on the home page for both react and figma but they're not really prominent right now. We do plan to update the homepage in terms of our target audience (and I agree with your points completely) + also considering extracting headless components into an open sourced package

**Comment by blvdmitry** [comment]
Thanks for all the feedback you're providing by the way. We receive some requests over email with quite specific requests for the product development, so it's always nice to have people on Github as well asking hard questions :)

**Comment by mmailaender** [comment]
You're welcome - maybe you have some Affiliate in the future, or something else ;P

Btw. noticed some cool point. This is a screenshot from Chakra. They have 8! components to deal with flex, grid, containers etc. You have atm two. View and Container - And in my opinion container is not more needed after View - So overall you would have only one component
![image](https://user-images.githubusercontent.com/87228994/209838833-4115ba48-9675-4d25-ba7c-f88d55ad633d.png)

I think this is an awesome USP - The easier View is to use and the better the documentation is, the stronger the USP will be :)

**Comment by blvdmitry** [comment]
Good point, actually the only thing Container also brings is margin: 0 auto style right now. All the rest comes from View already

**Comment by blvdmitry** [comment]
Added this to the index page redesign ticket planned for v2 in our planning board: https://blvworkspace.notion.site/64cf1f5713344a7383330e0402f43949?v=b88a6dbbcb9a4faeb867d40d09ec0b12
