### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#99]
Searching for e.g. SVG is not showing the Icon Utility.
![image](https://user-images.githubusercontent.com/87228994/209777928-0e155075-fa79-46f1-ba59-414d0d083390.png)

It would be helpful, to have also full text search results.

**Comment by blvdmitry** [comment]
Right now we have our search implemented with keyword support. Do you think adding a bunch more keywords to the components could already contribute to the cause? Or was there something you would want to be able to search specifically atm that you can't do? 

I fully agree that full-text search is better but I'm trying to understand if it's worth it at this point, considering that we can cover a lot with keywords

**Comment by mmailaender** [comment]
In my case, it was that searching for `svg` was not showing the Icon component. So probably yes, this could be covered as keyword, too :)

**Comment by blvdmitry** [comment]
Merged it just now for the next release
